<!--
/** 
 * @package     Ndsl_orderstatus
 * @author      Ndsl Team <gautam@ndslindia.com>
 * @copyright   Copyright (c) 2014 - Net Distribution Services Pvt Ltd. (http://ndslindia.com/)  
 */
-->
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td><h3 class="icon-head head-tax-rate-importExport"><?php echo Mage::helper('orderstatus')->__('Import Orderstatus Code') ?></h3></td>
        </tr>
    </table>
</div>
<div class="entry-edit">
    <div class="box-left">
        <form id="import_form" action="<?php echo $this->getUrl('*/*/import') ?>" method="post" enctype="multipart/form-data">
            <?php echo $this->getBlockHtml('formkey')?>
            <div class="entry-edit-head" style="width:925px;>
                <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('orderstatus')->__('Import Order Status Code') ?></h4>
            </div>

            <fieldset>
            <table class="form-list" cellspacing="0">
                <colgroup class="label"/>
                <colgroup class="value"/>
                <tbody">
                    <tr>
                         <td><?php echo Mage::helper('orderstatus')->__('Order Comment') ?></td>
                        <td class="value">
                            <input type="text" name="comments" class="input-file" value="" style="width:700px;"/>
                        </td>
                    </tr>
                    <tr>
                         <td><?php echo Mage::helper('orderstatus')->__('Order Status') ?></td>
                        <td class="value">
                            <select id="status" name="orderstatus_code" class="required-entry required-entry select">
                                <?php var_dump($this->getSataus());?>
                                <?php foreach ($this->getSataus() as $_code=>$_name): ?>
                                    <option value="<?php echo $_code ?>"><?php echo $_name ?></option>
                                <?php endforeach; ?>
                            </select>
                        </td>
                    </tr>
                    <tr>
                         <td><?php echo Mage::helper('orderstatus')->__('Create Invoice') ?></td>
                        <td class="value">
                            <input type="checkbox" name="createinvoce" value="1">
                            <p class="nm">
                                <small><?php echo Mage::helper('orderstatus')->__('cheacking this will conver order state to processing'); ?></small>
                            </p>
                        </td>
                    </tr>
                    <tr>
                        <td class="label">
                            <label><?php echo Mage::helper('orderstatus')->__('Import File') ?></label>
                        </td>
                        <td class="value">
                            <input type="file" name="import_orderstatus_file" class="input-file required-entry"/>
                            <p class="nm">
                                <small><?php echo Mage::helper('orderstatus')->__('Line format:'). ' "'.Mage::helper('orderstatus')->__('orderid').'"'; ?></small>
                            </p>
                        </td>
                    </tr>
                    <tr>
                        <td>&nbsp;</td>
                        <td class="value">
                            <?php $button_label = Mage::helper('orderstatus')->__('Import'); ?>
                            <?php echo $this->getButtonHtml($button_label, "this.form.submit();displayLoadingMask();") ?>
                        </td>
                    </tr>
                </tbody>
            </table>
            </fieldset>

        </form>
        <script type="text/javascript">
            var importForm = new varienForm('import_form');

            function displayLoadingMask()
            {
                var loaderArea = $$('#html-body .wrapper')[0]; // Blocks all page
                Position.clone($(loaderArea), $('loading-mask'), {offsetLeft:-2});
                toggleSelectsUnderBlock($('loading-mask'), false);
                Element.show('loading-mask');
            }
        </script>
    </div>
    <div class="clear"></div>
</div>
